# Generated by Django 3.1.7 on 2021-03-31 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='connect4/static/connect4/profile.jpg', upload_to='connect4/static/connect4/images')),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_ties', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField()),
                ('player1_color', models.CharField(max_length=7)),
                ('player2_color', models.CharField(max_length=7)),
                ('game_over', models.BooleanField(null=True)),
                ('moves_played', models.IntegerField(default=0)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='connect4.profile')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='connect4.profile')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='connect4.profile')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turn', to='connect4.profile')),
            ],
        ),
    ]
